# Programming-for-Data-Analysis-Assignment
# Richard Deegan 

# Porblem Statement:

The following assignment concerns the numpy.random package in Python. You are
required to create a Jupyter notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.

Deliverables:

1. Explain the overall purpose of the package.

2. Explain the use of the “Simple random data” and “Permutations” functions.

3. Explain the use and purpose of at least five “Distributions” functions.

4. Explain the use of seeds in generating pseudorandom numbers.


# Explain the overall purpose of the package 

Numpy’s random number produces pseudo random numbers using combinations of a **BitGenerator** to create sequences and a **Generator** to use those sequences to sample from different statistical distributions:

A **random bit generator** is a system whose output consists of fully unpredictable (i.e., statistically independent and unbiased) bits. In security applications, the unpredictability of the output implies that the generator must be also not observable and not manipulable by any attacker.

A random bit generator basically differs with respect to a  pseudorandom number generator, because the complete knowledge of the generator structure and of whatever previously generated sequence does not result in any knowledge of any other bit. This means that the entropy of a sequence of n output bits should be ideally equal to n. On the contrary, the entropy of a sequence of n output bits of a pseudorandom generator cannot be greater than its seed, whatever n is.

Since pseudorandom generators are suitable in those applications where just a flat statistic is needed, random generators are suitable in applications where unpredictability is also needed. [1]

The **Generator** provides access to a wide range of distributions. The Generator relies on an additional BitGenerator to manage state and generate the random bits, which are then transformed into random values from useful distributions. The default BitGenerator used by Generator is PCG64, which has better statistical properties than the legacy MT19937 used in RandomState  The BitGenerator can be changed by passing an instantized BitGenerator to Generator. [2]





# Smple Random Data

Simple random data is broken down into four sub sections.
1. Integers
2. Random
3. Choice
4. Bytes

Simple random data is used 


In [4]:
import numpy as np

np.random.default_rng

from numpy.random import Generator, PCG64

rg = Generator(PCG64())

rg.standard_normal()



2.4181636401268953

In [ ]:
# integers 

In [11]:
rng = np.random.default_rng()

rng.integers(5, size=5)



array([0, 4, 1, 1, 1], dtype=int64)

In [13]:
rng.integers(1,size=(2, 4))

array([[2, 3, 4, 0],
       [0, 2, 2, 0]], dtype=int64)

In [ ]:
# random

In [30]:
rng.random((3,2)) 

array([[0.01485691, 0.24797242],
       [0.22980485, 0.66330891],
       [0.89705817, 0.69503938]])

In [ ]:
## choice 

In [40]:
rng.choice(5, 3)

array([4, 1, 1], dtype=int64)

In [42]:
rng.choice(5, 100, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3, 3, 2, 2, 0, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 0, 2, 3, 3,
       3, 2, 2, 3, 3, 0, 3, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3, 3, 0, 2, 3, 3,
       3, 0, 2, 0, 3, 2, 2, 0, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 3,
       2, 3, 3, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 2,
       2, 3, 2, 2, 3, 2, 2, 3, 3, 2, 2, 3], dtype=int64)

In [ ]:
## Bytes 

In [48]:
np.random.default_rng().bytes(5)

b'd\xf2\xf3;\x9c'

# Permutations 

In [51]:
arr = np.arange(10)
rng.shuffle(arr)
arr

array([0, 2, 5, 8, 4, 1, 3, 7, 9, 6])

In [77]:
rng.permutation([1, 4, 2])

array([2, 1, 4])

# References

[1] Encyclopedia of Cryptography and Security https://link.springer.com/referenceworkentry/10.1007%2F978-1-4419-5906-5_514
[2] Random sampling (numpy.random) https://numpy.org/doc/stable/reference/random/index.html
[3] Simple random data https://numpy.org/doc/stable/reference/random/generator.html#simple-random-data
[4] Generating Random Numbers With NumPy https://chrisalbon.com/python/basics/generating_random_numbers_with_numpy/
[5] Random Numbers in NumPy https://www.w3schools.com/python/numpy_random.asp